apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{- include "webflux-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    {{- include "webflux-demo.selectorLabels" . | nindent 4 }}
